baseURL = 'https://badgerbadgerbadgerbadger.dev/'
languageCode = 'en-gb'
title = 'Badger Badger Badger Badger'
theme = "hugo-ficurinia"

defaultContentLanguage = "en"

cleanDestinationDir = true
copyright = "Shaun Das - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."
googleAnalytics = "UA-66106064-2"

[params]
    author = "Shaun Das"
    description = "A place for my thoughts."

    imageInArticlePreview = true
    fitImageInArticlePreview = false
    bigArticleTitle = false
    paperCards = true

    mainFontSizeMultiplier = 0.9

    showRss = false
    enableRelatedArticles = true

    commento = "https://commento.badgerbadgerbadgerbadger.dev/js/commento.js"

[menu]
    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

    [[menu.icons]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/badgerbbbadger"
    weight = 12

    [[menu.icons]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/badgerbadgerbadgerbadger/"
    weight = 10

