<template>
    <Layout>
        <h1>
            Hire Me!
        </h1>

        <p>
            Hi, I'm Shaun! I'm a passionate Principal Software Engineer with experience in back-end software development
            and developer tooling, interested in solving problems, sharing knowledge and enhancing developer
            productivity. Quick and dirty hacks then end up becoming a standalone project that increase team velocities
            are my speciality.
        </p>

        <p>
        <h2>Experience</h2>

        <ul>
            <li>
                <h3>Sentiance</h3>
            </li>
        </ul>
        </p>
    </Layout>
</template>